name: Unit Test
run-name: ${{ github.workflow }}; Trigger ${{ github.ref_name }}; Runner ${{ github.actor }}
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - .github/**/*
      - ./**/*.json
      - .stylelintrc.js
      - .stylelintignore
      - .eslintignore
      - .gitignore
      - .prettierignore
      - README.md
      - yarn.lock
      - config/**/*
      - webpack.config.ts
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Install Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
  unitTest:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: test
        run: pnpm test:unit
